// ── Prompt Hub Data ──────────────────────────────────────────────
// Each collection has a slug, belongs to a category group, and contains
// 5–8 individual ready-to-use prompts.

export interface Prompt {
  id: string;
  title: string;
  prompt: string;
  tags: string[];
}

export interface PromptCollection {
  slug: string;
  title: string;
  description: string;
  emoji: string;
  category: string;          // group heading on the hub page
  promptCount: number;
  prompts: Prompt[];
}

// ── Category groups (controls section headings on hub page) ────
export const CATEGORY_GROUPS = [
  { id: 'marketing-sales', label: 'Marketing & Sales', color: '#e11d48' },
  { id: 'writing-content', label: 'Writing & Content', color: '#8b5cf6' },
  { id: 'coding-dev', label: 'Coding & Development', color: '#0ea5e9' },
  { id: 'business-strategy', label: 'Business & Strategy', color: '#f59e0b' },
  { id: 'education-learning', label: 'Education & Learning', color: '#10b981' },
  { id: 'image-design', label: 'Image & Design', color: '#ec4899' },
  { id: 'productivity', label: 'Productivity & Workflow', color: '#6366f1' },
  { id: 'data-analytics', label: 'Data & Analytics', color: '#14b8a6' },
];

// ── All collections ────────────────────────────────────────────
export const PROMPT_COLLECTIONS: PromptCollection[] = [

  // ═══════════════════════════════════════════════════════════════
  // MARKETING & SALES
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-social-media',
    title: 'Prompts for Social Media',
    description: 'Create scroll-stopping posts, captions, and strategies for Instagram, LinkedIn, Twitter/X, and TikTok.',
    emoji: '📱',
    category: 'marketing-sales',
    promptCount: 35,
    prompts: [
      { id: 'sm-1', title: 'Viral LinkedIn Post', prompt: 'Write a LinkedIn post about [TOPIC] that starts with a bold, contrarian hook in the first line. Use short paragraphs (1-2 sentences max). Include a personal anecdote or lesson learned. End with a question to drive comments. Format: Hook → Story → Insight → CTA question. Tone: professional but conversational, no jargon.', tags: ['LinkedIn', 'Viral', 'Hook'] },
      { id: 'sm-2', title: 'Instagram Carousel Script', prompt: 'Create a 10-slide Instagram carousel about [TOPIC]. Slide 1: Bold headline with a promise (e.g., "5 things I wish I knew…"). Slides 2-9: One key point per slide with a short explanation (max 30 words). Slide 10: Summary + CTA ("Save this for later" or "Follow for more"). Include suggested alt text for accessibility.', tags: ['Instagram', 'Carousel', 'Visual'] },
      { id: 'sm-3', title: 'Twitter/X Thread Generator', prompt: 'Write a 10-tweet thread about [TOPIC]. Tweet 1: Hook that creates curiosity (use a number or bold claim). Tweets 2-9: One actionable insight per tweet, each starting with a number or emoji. Tweet 10: Summary + "Follow me for more on [NICHE]." Keep each tweet under 280 characters. Add a "🧵👇" to the first tweet.', tags: ['Twitter', 'Thread', 'Engagement'] },
      { id: 'sm-4', title: 'TikTok Script & Hook Ideas', prompt: 'Write a 60-second TikTok video script about [TOPIC]. Structure:\n\nHOOK (first 3 seconds): Give 3 hook options that stop the scroll — use "POV:", "Wait for it:", or a bold claim.\nBODY (40 seconds): 3-4 key points delivered in a punchy, conversational tone. Include on-screen text suggestions.\nCTA (last 5 seconds): Tell viewers what to do — comment, share, follow.\n\nAlso suggest: trending audio style, hashtags (5-7), and best posting time.', tags: ['TikTok', 'Script', 'Hooks'] },
      { id: 'sm-5', title: 'Social Media Content Calendar', prompt: 'Create a 2-week social media content calendar for a [INDUSTRY] brand. For each day provide:\n- Platform (Instagram / LinkedIn / Twitter)\n- Content type (carousel, reel, story, post, thread)\n- Topic / angle\n- Caption hook (first line)\n- Best posting time\n- Hashtags (5-7)\n\nInclude a mix of: educational (40%), entertaining (30%), promotional (20%), and community (10%) posts. Format as a table.', tags: ['Calendar', 'Strategy', 'Planning'] },
      { id: 'sm-6', title: 'Hashtag Research & Strategy', prompt: 'For the niche [YOUR NICHE], generate a comprehensive hashtag strategy:\n\n1. 10 high-volume hashtags (500K+ posts) for reach\n2. 10 medium-volume hashtags (50K-500K) for discoverability\n3. 10 low-volume/niche hashtags (under 50K) for targeted engagement\n4. 5 branded hashtag ideas\n5. 3 trending hashtags to leverage this week\n\nFor each, explain WHY it works for this niche. Also list 5 hashtags to AVOID (overused/spammy).', tags: ['Hashtags', 'Research', 'Growth'] },
    ],
  },

  {
    slug: 'prompts-for-email-marketing',
    title: 'Prompts for Email Marketing',
    description: 'Write high-converting email sequences, newsletters, and cold outreach campaigns.',
    emoji: '📧',
    category: 'marketing-sales',
    promptCount: 35,
    prompts: [
      { id: 'em-1', title: 'Welcome Email Sequence', prompt: 'Write a 5-email welcome sequence for a [PRODUCT/SERVICE] that just got a new subscriber. For each email provide:\n\n- Subject line (with an A/B variant)\n- Preview text\n- Email body (150-200 words)\n- CTA button text\n- Send timing (e.g., "Day 0, immediately after signup")\n\nSequence flow: Email 1: Warm welcome + quick win. Email 2: Your story/mission. Email 3: Best content/resource. Email 4: Social proof / testimonial. Email 5: Soft pitch with special offer.\n\nTone: friendly, personal, not salesy.', tags: ['Welcome', 'Sequence', 'Onboarding'] },
      { id: 'em-2', title: 'Cold Outreach Email', prompt: 'Write a cold outreach email to [TARGET ROLE] at [TYPE OF COMPANY]. The goal is to [GOAL — e.g., book a demo call].\n\nRequirements:\n- Subject line under 6 words (3 options)\n- Opening line that is personalized (use a placeholder like {{company_recent_news}})\n- One sentence about their likely pain point\n- One sentence about how you solve it (no feature dumping)\n- Social proof in one line (e.g., "We helped [Similar Company] achieve X")\n- Clear, low-friction CTA (e.g., "Worth a 15-min chat?")\n- Total length: under 100 words\n- Also write 2 follow-up emails (Day 3 and Day 7)', tags: ['Cold Email', 'Outreach', 'B2B'] },
      { id: 'em-3', title: 'Newsletter Issue Template', prompt: 'Write a weekly newsletter issue about [TOPIC/INDUSTRY]. Structure:\n\n1. **Subject line** — curiosity-driven, under 50 characters (3 options)\n2. **Intro** (2-3 sentences) — hook the reader with a hot take or question\n3. **Story of the week** (100 words) — one key development with your take\n4. **3 Quick links** — title + 1-sentence summary for each\n5. **Tip of the week** — one actionable insight readers can use today\n6. **CTA** — ask readers to reply, share, or check something out\n\nTone: knowledgeable friend, not corporate. Use "you" language.', tags: ['Newsletter', 'Weekly', 'Template'] },
      { id: 'em-4', title: 'Re-engagement Campaign', prompt: 'Write a 3-email re-engagement sequence for subscribers who haven\'t opened an email in 90+ days for [PRODUCT/SERVICE].\n\nEmail 1 ("We miss you"): Acknowledge the silence, share what\'s new (2-3 bullet points), offer a "welcome back" incentive.\nEmail 2 ("Last chance"): Create urgency — "We\'re cleaning our list." Ask them to click one button to stay.\nEmail 3 ("Goodbye"): Respectful farewell, mention they\'re being removed, give one final link to re-subscribe.\n\nFor each: subject line, preview text, body (100 words max), CTA.', tags: ['Re-engagement', 'Win-back', 'Retention'] },
      { id: 'em-5', title: 'Product Launch Email Sequence', prompt: 'Write a 4-email product launch sequence for [PRODUCT NAME] launching on [DATE].\n\nEmail 1 (7 days before): Teaser — build anticipation without revealing everything. "Something big is coming."\nEmail 2 (3 days before): Behind the scenes — show the making-of, the why behind the product.\nEmail 3 (Launch day): The big reveal — features, benefits, launch offer, social proof.\nEmail 4 (2 days after): Last chance — urgency, FAQ objections handled, final CTA.\n\nFor each: subject line (2 options), body, CTA. Tone: excited but not hypey.', tags: ['Launch', 'Product', 'Sequence'] },
    ],
  },

  {
    slug: 'prompts-for-seo',
    title: 'Prompts for SEO',
    description: 'Keyword research, on-page optimization, meta tags, and content briefs for search engine ranking.',
    emoji: '🔍',
    category: 'marketing-sales',
    promptCount: 35,
    prompts: [
      { id: 'seo-1', title: 'Keyword Cluster Generator', prompt: 'For the seed keyword "[KEYWORD]", generate a comprehensive keyword cluster:\n\n1. **Primary keyword** + search intent (informational/transactional/navigational)\n2. **10 secondary keywords** (long-tail variations) with estimated difficulty (low/med/high)\n3. **10 related questions** people ask (for FAQ sections & People Also Ask)\n4. **5 LSI keywords** (semantically related terms to include naturally)\n5. **Content gap opportunities** — 3 angles competitors likely haven\'t covered\n\nFormat as a table. Also suggest the ideal content type for each cluster (blog post, landing page, comparison page, etc.).', tags: ['Keywords', 'Clusters', 'Research'] },
      { id: 'seo-2', title: 'SEO Blog Post Brief', prompt: 'Create a detailed SEO content brief for the keyword "[TARGET KEYWORD]".\n\nInclude:\n- **Target word count** (based on competitive analysis estimate)\n- **Search intent** and ideal content format\n- **Suggested title** (with primary keyword, under 60 chars) — 3 options\n- **Meta description** (with keyword, under 155 chars) — 2 options\n- **URL slug** suggestion\n- **H2 headings** (6-8 sections) with H3 sub-points\n- **Key points to cover** under each heading\n- **Internal linking opportunities** (suggest 3-5 related topics to link to)\n- **External source suggestions** (types of data/stats to reference)\n- **Featured snippet opportunity** — format a section to win the snippet (paragraph, list, or table)', tags: ['Brief', 'Blog', 'On-Page'] },
      { id: 'seo-3', title: 'Meta Title & Description Generator', prompt: 'Generate SEO-optimized meta titles and descriptions for the following pages on a [TYPE OF WEBSITE] website:\n\n1. Homepage\n2. About page\n3. Product/Service page for [PRODUCT]\n4. Blog category page for [CATEGORY]\n5. Contact page\n\nFor each page provide:\n- 3 title tag options (under 60 characters, keyword-rich)\n- 2 meta description options (under 155 characters, include CTA)\n- Suggested Open Graph title and description (can be slightly different)\n\nPrimary brand keyword: [KEYWORD]. Secondary keywords: [LIST].', tags: ['Meta Tags', 'Titles', 'SERP'] },
      { id: 'seo-4', title: 'Technical SEO Audit Checklist', prompt: 'Create a comprehensive technical SEO audit checklist for [WEBSITE URL]. Organize into these sections:\n\n1. **Crawlability** — robots.txt, sitemap, crawl errors, orphan pages\n2. **Indexation** — indexed page count, noindex tags, canonical tags\n3. **Page Speed** — Core Web Vitals (LCP, FID, CLS), image optimization, render-blocking resources\n4. **Mobile** — mobile-friendliness, viewport, tap targets\n5. **Structure** — URL structure, breadcrumbs, internal linking depth\n6. **Security** — HTTPS, mixed content\n7. **Schema** — structured data implementation (Article, Product, FAQ, etc.)\n\nFor each item: what to check, how to check it (tool), and how to fix common issues.', tags: ['Technical', 'Audit', 'Checklist'] },
      { id: 'seo-5', title: 'Competitor SEO Analysis', prompt: 'Analyze the SEO strategy of [COMPETITOR URL] and create an actionable report:\n\n1. **Top ranking keywords** — estimate their top 10 organic keywords and which pages rank\n2. **Content strategy** — what types of content do they publish? How often? Average word count?\n3. **Backlink profile** — what types of sites link to them? Any patterns?\n4. **Content gaps** — topics they rank for that we don\'t\n5. **Weaknesses** — areas where their SEO is weak (thin content, slow pages, missing schema)\n6. **Action items** — 5 specific things we should do to outrank them, prioritized by impact vs effort\n\nFormat as a strategic brief I can share with my team.', tags: ['Competitor', 'Analysis', 'Strategy'] },
    ],
  },

  {
    slug: 'prompts-for-sales',
    title: 'Prompts for Sales',
    description: 'Sales scripts, objection handling, proposal writing, and pipeline management prompts.',
    emoji: '🤝',
    category: 'marketing-sales',
    promptCount: 35,
    prompts: [
      { id: 'sales-1', title: 'Discovery Call Script', prompt: 'Write a discovery call script for selling [PRODUCT/SERVICE] to [TARGET BUYER PERSONA].\n\nStructure:\n1. **Opening** (30 sec): Build rapport, set agenda, confirm time\n2. **Situation questions** (5 questions): Understand their current state\n3. **Problem questions** (5 questions): Uncover pain points\n4. **Implication questions** (3 questions): Make them feel the cost of inaction\n5. **Need-payoff questions** (3 questions): Get them to articulate the value of a solution\n6. **Bridge to demo/next step**: Transition naturally\n7. **Common objections & responses** (top 5)\n\nTone: consultative, curious, not pushy. Each question should flow naturally from the previous answer.', tags: ['Discovery', 'Script', 'SPIN'] },
      { id: 'sales-2', title: 'Objection Handling Playbook', prompt: 'Create an objection handling playbook for [PRODUCT/SERVICE]. For each of these common objections, provide a response using the LAER framework (Listen, Acknowledge, Explore, Respond):\n\n1. "It\'s too expensive"\n2. "We\'re already using [COMPETITOR]"\n3. "I need to talk to my team/boss"\n4. "We don\'t have budget right now"\n5. "Can you send me more information?"\n6. "We\'re not ready to make a change"\n7. "I don\'t see how this is different"\n8. "We tried something similar and it didn\'t work"\n\nFor each: the framework response, a specific example script, and a follow-up question to keep the conversation going.', tags: ['Objections', 'Playbook', 'Closing'] },
      { id: 'sales-3', title: 'Proposal / Quote Email', prompt: 'Write a professional proposal email to send after a successful demo of [PRODUCT/SERVICE] to [CLIENT NAME] at [COMPANY].\n\nInclude:\n1. Thank them for their time, reference a specific point from the conversation\n2. Recap their key challenges (3 bullet points)\n3. How our solution addresses each challenge\n4. Pricing summary (use placeholder tiers)\n5. What\'s included (deliverables/features)\n6. Timeline for implementation\n7. Next steps with a specific date suggestion\n8. P.S. line with a relevant case study or social proof\n\nTone: confident, helpful, not desperate. Under 400 words.', tags: ['Proposal', 'Follow-up', 'Deal'] },
      { id: 'sales-4', title: 'LinkedIn Sales Outreach', prompt: 'Write a 3-touch LinkedIn outreach sequence to connect with [TARGET ROLE] at [INDUSTRY] companies.\n\nTouch 1 (Connection request): A personalized note under 300 characters. Reference something specific — their recent post, company news, or shared connection.\n\nTouch 2 (Day 2 after accepted): Thank them, share one valuable insight or resource related to their role (NOT a pitch). End with an open question.\n\nTouch 3 (Day 5): Soft pitch — mention a relevant pain point, share a brief success story, suggest a quick chat. Keep it under 150 words.\n\nAlso provide: 3 profile headline suggestions that attract inbound leads.', tags: ['LinkedIn', 'Outreach', 'Prospecting'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // WRITING & CONTENT
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-writing',
    title: 'Prompts for Writing',
    description: 'Blog posts, articles, essays, and long-form content creation with structured frameworks.',
    emoji: '✍️',
    category: 'writing-content',
    promptCount: 35,
    prompts: [
      { id: 'wr-1', title: 'SEO Blog Post Writer', prompt: 'Write a comprehensive, SEO-optimized blog post about "[TOPIC]".\n\nRequirements:\n- **Length**: 1,500-2,000 words\n- **Structure**: H1 title (with primary keyword) → intro with hook → 5-7 H2 sections → conclusion with CTA\n- **SEO**: Naturally include the keyword "[KEYWORD]" 5-8 times. Add 3 internal link placeholders [INTERNAL LINK: topic] and 2 external source placeholders.\n- **Tone**: [TONE — e.g., authoritative yet approachable]\n- **Target audience**: [AUDIENCE]\n- Include a TL;DR summary at the top, a key takeaways box, and end with 3 FAQs (formatted for featured snippet).\n- Write in active voice, short paragraphs (2-3 sentences), and use transition words.', tags: ['Blog', 'SEO', 'Long-form'] },
      { id: 'wr-2', title: 'Engaging Article Introduction', prompt: 'Write 5 different opening paragraphs for an article about "[TOPIC]". Each should use a different hook technique:\n\n1. **Startling statistic**: Open with a surprising data point\n2. **Story/anecdote**: Start with a brief relatable scenario\n3. **Contrarian statement**: Challenge a common belief\n4. **Question**: Ask a thought-provoking question\n5. **Quote**: Start with a relevant quote and build on it\n\nEach intro should be 3-4 sentences, create curiosity, and make the reader want to continue. End each with a transition sentence that previews the article\'s value.', tags: ['Introduction', 'Hooks', 'Articles'] },
      { id: 'wr-3', title: 'Content Repurposer', prompt: 'Take this blog post content and repurpose it into 7 different formats:\n\n[PASTE YOUR BLOG POST OR KEY POINTS]\n\n1. **Twitter/X thread** (8-10 tweets)\n2. **LinkedIn post** (with hook + story + insight + CTA)\n3. **Instagram carousel** (10 slides — text only, concise)\n4. **YouTube video script** (5-minute outline with intro, points, outro)\n5. **Email newsletter** (subject line + 200-word body)\n6. **Podcast talking points** (bullet points for a 10-min segment)\n7. **Infographic outline** (data points, flow, visual suggestions)\n\nFor each format, adapt the tone and structure to fit the platform.', tags: ['Repurpose', 'Multi-channel', 'Content'] },
      { id: 'wr-4', title: 'Thought Leadership Article', prompt: 'Write a thought leadership article on "[TOPIC]" for a [INDUSTRY] audience.\n\nStructure:\n- **Headline**: Bold, opinion-driven (not clickbait)\n- **Lede** (first paragraph): State your thesis clearly\n- **Context**: Why this matters now (2 paragraphs with trends/data)\n- **Your argument**: 3 key points with supporting evidence\n- **Counterargument**: Acknowledge the strongest opposing view and respond\n- **Call to action**: What should the reader do differently?\n\nTone: confident, backed by experience, not preachy. Use "I" sparingly — focus on "we" and "you." Include 2-3 real-world examples (or realistic placeholders). Length: 1,000-1,200 words.', tags: ['Thought Leadership', 'Opinion', 'Industry'] },
      { id: 'wr-5', title: 'Case Study Writer', prompt: 'Write a compelling case study about how [COMPANY/CLIENT] used [PRODUCT/SERVICE] to achieve [RESULT].\n\nFormat:\n1. **Headline**: "[Company] achieved [Result] with [Product]"\n2. **At a glance** box: Industry, company size, challenge, solution, results (with numbers)\n3. **The Challenge** (200 words): What problem did they face? What was at stake?\n4. **The Solution** (200 words): How did they implement your product? What was the process?\n5. **The Results** (200 words): Specific metrics, before/after comparison, timeline\n6. **Quote**: A testimonial from the client (write a realistic placeholder)\n7. **Key Takeaways**: 3 bullet points other companies can learn from\n\nTone: story-driven, specific, not a product brochure.', tags: ['Case Study', 'B2B', 'Storytelling'] },
      { id: 'wr-6', title: 'Newsletter Content Ideas', prompt: 'Generate 20 newsletter content ideas for a [NICHE/INDUSTRY] newsletter called "[NEWSLETTER NAME]".\n\nFor each idea provide:\n- Subject line (curiosity-driven, under 50 characters)\n- Main angle / hook in one sentence\n- Content type: hot take, tutorial, curated links, interview, behind-the-scenes, or data-driven\n\nMix should be: 30% educational, 25% curated, 20% opinion, 15% actionable tips, 10% personal stories.\n\nAlso suggest: 5 recurring segments (like "Tool of the Week" or "Hot Take Tuesday") that could become signature elements.', tags: ['Newsletter', 'Ideas', 'Planning'] },
    ],
  },

  {
    slug: 'prompts-for-creative-writing',
    title: 'Prompts for Creative Writing',
    description: 'Fiction, storytelling, character development, world-building, and narrative techniques.',
    emoji: '📚',
    category: 'writing-content',
    promptCount: 30,
    prompts: [
      { id: 'cw-1', title: 'Character Development Sheet', prompt: 'Create a detailed character profile for a [GENRE] story:\n\n**Basics**: Full name, age, occupation, physical description (distinctive features, how they carry themselves)\n\n**Psychology**: Core motivation, greatest fear, fatal flaw, moral code (one rule they\'d never break, one they\'d bend)\n\n**Background**: Key childhood event that shaped them, a secret they keep, their relationship with their family\n\n**Voice**: Write 3 sample dialogue lines that capture their unique speech pattern — vocabulary, rhythm, verbal tics\n\n**Arc**: Where do they start emotionally? What do they believe at the beginning that will be challenged? Where could they end up (best case vs worst case)?\n\n**Contradiction**: Give them one trait that contradicts their surface personality (e.g., a hardened detective who secretly writes poetry).', tags: ['Character', 'Fiction', 'Development'] },
      { id: 'cw-2', title: 'Story Opening Generator', prompt: 'Write 5 different opening paragraphs for a [GENRE] story about [BASIC PREMISE]. Each opening should use a different technique:\n\n1. **In medias res**: Drop the reader into the middle of action\n2. **Mystery/question**: Open with something unexplained or unsettling\n3. **Voice-driven**: A narrator with a distinctive, compelling voice\n4. **Sensory immersion**: Ground the reader in a vivid setting using all 5 senses\n5. **Dialogue**: Start with a conversation that reveals conflict\n\nEach should be 100-150 words, hook the reader immediately, and establish the story\'s tone. After each opening, write one sentence explaining what narrative promise it makes to the reader.', tags: ['Opening', 'Hook', 'Fiction'] },
      { id: 'cw-3', title: 'Plot Structure Builder', prompt: 'Using the [THREE-ACT / HERO\'S JOURNEY / SAVE THE CAT] structure, outline a complete plot for a [GENRE] story about [PREMISE].\n\nFor each major plot point provide:\n- **What happens** (2-3 sentences)\n- **Character emotional state**\n- **Stakes** (what\'s at risk?)\n- **Tension source** (what conflict drives this scene?)\n\nAlso include:\n- 3 possible subplots that reinforce the main theme\n- The story\'s **controlling idea** in one sentence (e.g., "Love conquers fear when...")\n- **Ticking clock**: What creates urgency?\n- **Mirror moment**: Where does the protagonist see themselves clearly?\n- Suggest 3 possible endings (happy, bittersweet, dark) and which best serves the theme.', tags: ['Plot', 'Structure', 'Outline'] },
      { id: 'cw-4', title: 'Dialogue Workshop', prompt: 'Write a dialogue scene between [CHARACTER A] and [CHARACTER B] where [SITUATION — e.g., one is breaking bad news to the other].\n\nRequirements:\n- Each character should have a distinct voice (vocabulary, sentence length, verbal habits)\n- Include subtext — what they mean should differ from what they say\n- Add brief action beats between lines (not just "he said/she said")\n- Build tension — the conversation should escalate\n- Include at least one moment of silence or interruption\n- End the scene on a line that changes everything\n\nAfter the scene, explain: What does each character want? What are they hiding? Who has more power, and does it shift?', tags: ['Dialogue', 'Scene', 'Subtext'] },
      { id: 'cw-5', title: 'World-Building Framework', prompt: 'Build a detailed world for a [GENRE] story set in [SETTING].\n\nCover these areas:\n1. **Geography & Climate**: Key locations, how the environment shapes culture\n2. **Society & Power**: Who rules? What are the social classes? What creates conflict?\n3. **Economy**: What do people trade? What\'s valuable? Who\'s rich and who\'s poor?\n4. **Technology/Magic System**: What are the rules? What are the costs/limitations?\n5. **Culture**: One unique custom, one taboo, one form of art/entertainment\n6. **History**: One defining event that everyone remembers (like a war or discovery)\n7. **Daily life**: What does an ordinary day look like for a regular person?\n\nMake each element serve the story — connect at least 3 elements to potential plot conflicts.', tags: ['World-Building', 'Setting', 'Fantasy'] },
    ],
  },

  {
    slug: 'prompts-for-copywriting',
    title: 'Prompts for Copywriting',
    description: 'Headlines, landing pages, ads, and persuasion frameworks for high-converting copy.',
    emoji: '💎',
    category: 'writing-content',
    promptCount: 35,
    prompts: [
      { id: 'cp-1', title: 'Landing Page Copy Framework', prompt: 'Write complete landing page copy for [PRODUCT/SERVICE] targeting [AUDIENCE].\n\nSections:\n1. **Hero**: Headline (benefit-driven, under 10 words), sub-headline (address the pain), CTA button text\n2. **Problem**: 3 pain points the audience feels (use "you" language)\n3. **Solution**: How the product solves each pain point\n4. **Features → Benefits**: 4-6 features, each translated into a benefit\n5. **Social Proof**: 3 testimonial templates, a "used by" logos section, key metric\n6. **How It Works**: 3-step process\n7. **FAQ**: 5 objection-busting questions with answers\n8. **Final CTA**: Urgency + guarantee + button text\n\nUse the PAS (Problem-Agitate-Solve) framework throughout. Tone: confident, empathetic, zero fluff.', tags: ['Landing Page', 'PAS', 'Conversion'] },
      { id: 'cp-2', title: 'Headline Generator (50 Variants)', prompt: 'Generate 50 headline variations for [PRODUCT/SERVICE] that [VALUE PROPOSITION].\n\nOrganize into groups:\n- **How-To** (10): "How to [achieve result] without [pain point]"\n- **Number** (10): "[Number] ways to…" or "[Number] reasons why…"\n- **Question** (10): Curiosity-driven questions\n- **Testimonial-style** (5): "I [result] in [timeframe] using…"\n- **Negative/Warning** (5): "Stop doing [common mistake] if you want…"\n- **Command** (5): Direct, action-oriented\n- **Curiosity gap** (5): Create intrigue with an open loop\n\nFor each headline, rate its emotional appeal (1-5), clarity (1-5), and best use case (ad, email subject, landing page, blog title).', tags: ['Headlines', '50 Options', 'A/B Testing'] },
      { id: 'cp-3', title: 'Facebook/Google Ad Copy', prompt: 'Write ad copy for [PRODUCT/SERVICE] targeting [AUDIENCE] on [PLATFORM — Facebook/Google/Instagram].\n\nFor each platform, provide 3 ad variations:\n\n**Facebook/Instagram Ad:**\n- Primary text (125 characters for feed, 3 variants)\n- Headline (40 characters, 3 variants)\n- Description (30 characters)\n- CTA button recommendation\n\n**Google Search Ad:**\n- 3 headline options (30 chars each)\n- 2 description options (90 chars each)\n- Display URL path suggestions\n- Sitelink extension ideas (4)\n\nUse different angles: benefit-focused, problem-focused, social proof, urgency. Include negative keywords to avoid.', tags: ['Ads', 'Facebook', 'Google'] },
      { id: 'cp-4', title: 'Email Subject Line Generator', prompt: 'Generate 30 email subject lines for [TYPE OF EMAIL — e.g., product launch, newsletter, promotional] for [BRAND/PRODUCT].\n\nOrganize by technique:\n1. **Curiosity** (5): Create an open loop\n2. **Urgency** (5): Time-sensitive language\n3. **Personalization** (5): Use merge tags like {{first_name}}\n4. **Number/List** (5): "5 things…", "The 3 mistakes…"\n5. **Question** (5): Engage with a direct question\n6. **Emoji** (5): Strategic emoji use\n\nFor each: rate predicted open rate impact (low/medium/high) and note if it works better for cold vs warm audiences. Also list 5 spam trigger words to AVOID.', tags: ['Subject Lines', 'Email', 'Open Rate'] },
    ],
  },

  {
    slug: 'prompts-for-youtube',
    title: 'Prompts for YouTube',
    description: 'Video scripts, titles, thumbnails, descriptions, and channel strategy.',
    emoji: '🎬',
    category: 'writing-content',
    promptCount: 35,
    prompts: [
      { id: 'yt-1', title: 'YouTube Video Script', prompt: 'Write a full script for a [LENGTH]-minute YouTube video about "[TOPIC]".\n\nStructure:\n**HOOK (0:00-0:30)**: Start with a bold claim, question, or teaser. Retain viewers in the first 10 seconds.\n**INTRO (0:30-1:00)**: Brief context, what they\'ll learn, why it matters NOW.\n**MAIN CONTENT** (3-5 sections): Each section is:\n  - Section title (on-screen text suggestion)\n  - Key talking points (3-4 per section)\n  - B-roll/visual suggestions\n  - Transition to next section\n**CTA MID-ROLL**: "If you\'re finding this valuable, hit subscribe…"\n**CONCLUSION**: Recap key points, tease next video, end screen CTA.\n\nAlso provide: 5 title options, description with timestamps, 10 tags, and 3 thumbnail text ideas.', tags: ['Script', 'Full Video', 'Structure'] },
      { id: 'yt-2', title: 'YouTube Title & Thumbnail Ideas', prompt: 'Generate 10 YouTube title + thumbnail combinations for a video about "[TOPIC]" on a [NICHE] channel.\n\nFor each:\n- **Title** (under 60 characters, keyword-rich)\n- **Thumbnail concept**: Describe the image — facial expression, text overlay (max 4 words), colors, and composition\n- **Click-through appeal**: Why would someone click? What emotion does it trigger?\n\nTitle formulas to use: "I Tried [X] for [Time]", "Why [Common Thing] is a Lie", "[Number] [Things] That [Bold Claim]", "How [Ordinary Person] [Extraordinary Result]", "Stop [Doing This] — Do [This] Instead"\n\nAlso suggest: 3 A/B test pairs (same content, different angle) to test which gets higher CTR.', tags: ['Titles', 'Thumbnails', 'CTR'] },
      { id: 'yt-3', title: 'YouTube Description & Tags', prompt: 'Write an optimized YouTube description for a video titled "[VIDEO TITLE]" about [TOPIC].\n\nStructure:\n1. **First 2 lines** (visible before "Show More"): Hook + keyword-rich summary\n2. **Timestamps/Chapters**: Create 6-8 chapter markers with descriptive titles\n3. **Links section**: Placeholder links for resources mentioned\n4. **About section**: Brief channel description (2 sentences)\n5. **Hashtags**: 3 relevant hashtags\n\nAlso provide:\n- 15 tags (mix of broad and long-tail keywords)\n- Suggested end screen cards (video + subscribe)\n- Suggested pinned comment to boost engagement\n- 3 comment prompts to seed the comments section', tags: ['Description', 'Tags', 'SEO'] },
      { id: 'yt-4', title: 'YouTube Shorts Script', prompt: 'Write 5 YouTube Shorts scripts (under 60 seconds each) for the niche [NICHE].\n\nFor each Short:\n- **Hook** (first 2 seconds): One line that stops the scroll\n- **Content** (50 seconds): Quick, punchy delivery — one idea, one tip, or one story\n- **CTA** (last 5 seconds): Follow, subscribe, or watch the full video\n- **On-screen text** suggestions for each key moment\n- **Trending audio suggestion** (describe the vibe)\n\nTopics should mix: how-to tips, myths debunked, "things nobody tells you about…", before/after transformations, and "reply to comment" style.\n\nAlso provide: optimal posting time and 5 hashtags per Short.', tags: ['Shorts', 'Short-form', 'Viral'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // CODING & DEVELOPMENT
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-coding',
    title: 'Prompts for Coding',
    description: 'Generate, debug, refactor, and review code across multiple languages and frameworks.',
    emoji: '💻',
    category: 'coding-dev',
    promptCount: 35,
    prompts: [
      { id: 'code-1', title: 'React Component Generator', prompt: 'Create a production-ready React component for [DESCRIBE COMPONENT — e.g., "a searchable dropdown with multi-select"].\n\nRequirements:\n- TypeScript with proper interfaces/types\n- Tailwind CSS for styling\n- Accessible (ARIA attributes, keyboard navigation)\n- Responsive (mobile-first)\n- Include: loading state, empty state, error state\n- Use React hooks (useState, useEffect, useMemo as needed)\n- Add JSDoc comments for the component and its props\n- Export as default\n\nAlso provide:\n- Example usage code\n- List of props with descriptions\n- Any custom hooks extracted\n- Suggested unit test cases (just the test names, not full tests)', tags: ['React', 'TypeScript', 'Component'] },
      { id: 'code-2', title: 'Code Review Prompt', prompt: 'Review the following code for quality, security, and performance. Analyze it across these dimensions:\n\n```\n[PASTE YOUR CODE HERE]\n```\n\n1. **Bugs & Logic Errors**: Any incorrect behavior or edge cases missed?\n2. **Security**: SQL injection, XSS, auth issues, secrets exposure, input validation\n3. **Performance**: N+1 queries, unnecessary re-renders, memory leaks, O(n²) loops\n4. **Readability**: Naming, structure, comments, dead code\n5. **Best Practices**: Design patterns, DRY violations, error handling\n6. **Testing**: What\'s untestable? What edge cases need tests?\n\nFor each issue found:\n- Severity: 🔴 Critical / 🟡 Warning / 🔵 Suggestion\n- Line number (if applicable)\n- The problem\n- Suggested fix (with code)\n\nEnd with an overall code health score (1-10) and top 3 priorities.', tags: ['Code Review', 'Quality', 'Security'] },
      { id: 'code-3', title: 'API Endpoint Designer', prompt: 'Design a complete REST API for [FEATURE — e.g., "user authentication with email and OAuth"].\n\nFor each endpoint provide:\n- **Method & Path**: e.g., POST /api/auth/login\n- **Description**: What it does\n- **Request body/params**: JSON schema with types and validation rules\n- **Response**: Success (200/201) and error (400/401/404/500) response schemas\n- **Headers**: Required headers (auth, content-type)\n- **Rate limiting**: Suggested limits\n- **Example** request and response\n\nAlso include:\n- Database schema (SQL or document model) needed for this feature\n- Authentication middleware requirements\n- Error code enum/constants\n- Suggested integration test scenarios', tags: ['API', 'REST', 'Design'] },
      { id: 'code-4', title: 'Debug This Error', prompt: 'I\'m getting this error in my [LANGUAGE/FRAMEWORK] project:\n\n```\n[PASTE ERROR MESSAGE / STACK TRACE]\n```\n\nHere\'s the relevant code:\n```\n[PASTE CODE]\n```\n\nPlease:\n1. **Explain** what this error means in plain English\n2. **Root cause**: Why is this happening? Trace the execution path\n3. **Fix**: Provide the corrected code with comments explaining the changes\n4. **Prevention**: How to avoid this error in the future (linting rules, patterns, tests)\n5. **Related issues**: Are there similar potential bugs nearby in this code?\n\nIf you need more context (imports, config, package versions), tell me exactly what to provide.', tags: ['Debug', 'Error Fix', 'Troubleshoot'] },
      { id: 'code-5', title: 'Database Schema Designer', prompt: 'Design a database schema for [APPLICATION — e.g., "an e-commerce platform with products, orders, users, and reviews"].\n\nProvide:\n1. **Entity-Relationship diagram** (describe in text/ASCII)\n2. **SQL CREATE TABLE statements** for each table:\n   - Proper data types\n   - Primary keys, foreign keys, indexes\n   - NOT NULL constraints, defaults\n   - CHECK constraints where appropriate\n3. **Indexes**: Which columns need indexes and why\n4. **Common queries**: Write 5 queries this app would frequently run\n5. **Migration plan**: Order of table creation (respecting foreign keys)\n6. **Scaling considerations**: When this table hits 1M+ rows, what changes?\n\nDatabase: [PostgreSQL / MySQL / MongoDB]. Include comments explaining design decisions.', tags: ['Database', 'Schema', 'SQL'] },
      { id: 'code-6', title: 'Refactor This Code', prompt: 'Refactor the following code to improve readability, maintainability, and performance:\n\n```\n[PASTE YOUR CODE HERE]\n```\n\nApply these principles:\n1. **Single Responsibility**: Split functions that do too much\n2. **DRY**: Extract repeated patterns into reusable functions/utilities\n3. **Naming**: Rename variables and functions to be self-documenting\n4. **Error Handling**: Add proper try/catch, validation, and error messages\n5. **Modern Syntax**: Use current language features (ES2024, etc.)\n6. **Type Safety**: Add TypeScript types if applicable\n\nProvide:\n- The refactored code with comments explaining WHY each change was made\n- A before/after comparison of the key changes\n- Any new utility functions extracted\n- Estimated complexity reduction (Big-O if applicable)', tags: ['Refactor', 'Clean Code', 'Best Practices'] },
    ],
  },

  {
    slug: 'prompts-for-python',
    title: 'Prompts for Python',
    description: 'Python scripts, data processing, automation, and web scraping prompts.',
    emoji: '🐍',
    category: 'coding-dev',
    promptCount: 35,
    prompts: [
      { id: 'py-1', title: 'Python Script Generator', prompt: 'Write a Python script that [DESCRIBE WHAT IT SHOULD DO].\n\nRequirements:\n- Python 3.10+ syntax (match/case, type hints, f-strings)\n- Proper error handling with specific exception types\n- Logging instead of print statements (use logging module)\n- Docstrings for all functions (Google style)\n- Type hints for all function parameters and return values\n- argparse for command-line arguments (if applicable)\n- Configuration via environment variables or a config dict (not hardcoded)\n\nStructure the code as:\n1. Imports\n2. Constants/Config\n3. Helper functions\n4. Main logic\n5. if __name__ == "__main__": block\n\nAlso provide: requirements.txt, example usage command, and 3 test cases.', tags: ['Python', 'Script', 'Automation'] },
      { id: 'py-2', title: 'Data Processing Pipeline', prompt: 'Write a Python data processing pipeline that:\n1. Reads data from [SOURCE — e.g., CSV file, API, database]\n2. Cleans: handle missing values, remove duplicates, fix data types\n3. Transforms: [DESCRIBE TRANSFORMATIONS]\n4. Validates: Check data quality and log anomalies\n5. Outputs: [DESTINATION — e.g., cleaned CSV, database table, API call]\n\nUse pandas for data manipulation. Include:\n- Progress logging for large datasets\n- Memory-efficient chunked processing (for files > 1GB)\n- A summary report at the end (rows processed, rows dropped, time taken)\n- Error handling that doesn\'t crash on a single bad row\n- Config dict at the top for all parameters (file paths, thresholds, etc.)\n\nMake it re-runnable (idempotent) and add a --dry-run flag.', tags: ['Data', 'Pipeline', 'Pandas'] },
      { id: 'py-3', title: 'Web Scraper Builder', prompt: 'Write a Python web scraper for [WEBSITE/URL] to extract [WHAT DATA].\n\nUse the appropriate library:\n- **requests + BeautifulSoup** for static pages\n- **Playwright/Selenium** if JavaScript rendering is needed\n\nInclude:\n- Respectful scraping: rate limiting (1 request/second), user-agent rotation, robots.txt check\n- Retry logic with exponential backoff (3 retries)\n- Data extraction into structured format (list of dicts)\n- Export to CSV and JSON\n- Error handling for: connection errors, missing elements, changed page structure\n- Progress bar (tqdm)\n- Logging\n\nAlso provide:\n- Example output (first 3 records)\n- How to handle pagination\n- Legal disclaimer about checking ToS\n- requirements.txt', tags: ['Scraping', 'BeautifulSoup', 'Automation'] },
      { id: 'py-4', title: 'FastAPI Backend Starter', prompt: 'Create a FastAPI backend for [APPLICATION — e.g., "a todo app with user auth"].\n\nInclude:\n1. **Project structure** (folders and files)\n2. **Models**: Pydantic schemas for request/response\n3. **Routes**: CRUD endpoints with proper HTTP methods and status codes\n4. **Auth**: JWT-based authentication (login, register, protected routes)\n5. **Database**: SQLAlchemy models + async connection (SQLite for dev, Postgres ready)\n6. **Middleware**: CORS, request logging\n7. **Error handling**: Custom exception handlers\n8. **Config**: Environment variables via pydantic-settings\n\nProvide: main.py, models.py, routes.py, auth.py, database.py, config.py\nAlso: requirements.txt, .env.example, and Dockerfile.', tags: ['FastAPI', 'Backend', 'API'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // BUSINESS & STRATEGY
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-business-strategy',
    title: 'Prompts for Business Strategy',
    description: 'Business plans, market analysis, competitive research, and strategic planning.',
    emoji: '💼',
    category: 'business-strategy',
    promptCount: 35,
    prompts: [
      { id: 'biz-1', title: 'Business Plan Generator', prompt: 'Write a lean business plan for [BUSINESS IDEA] targeting [MARKET/AUDIENCE].\n\nSections:\n1. **Executive Summary** (150 words): What, who, why, how, and the ask\n2. **Problem**: What pain point exists? How big is it? (Use TAM/SAM/SOM framework)\n3. **Solution**: Your product/service, key differentiator, unfair advantage\n4. **Business Model**: How you make money — pricing, revenue streams, unit economics\n5. **Market Analysis**: Target customer persona, market size, growth trends\n6. **Competition**: 3 competitors with your positioning (use a 2x2 matrix framework)\n7. **Go-to-Market**: Customer acquisition strategy for first 100, then first 1,000 customers\n8. **Team**: What roles are needed and why\n9. **Financial Projections**: Year 1-3 revenue estimates with key assumptions\n10. **The Ask**: What you need (funding, partnerships, etc.)\n\nTone: confident, data-driven, concise.', tags: ['Business Plan', 'Startup', 'Strategy'] },
      { id: 'biz-2', title: 'SWOT Analysis Generator', prompt: 'Conduct a comprehensive SWOT analysis for [COMPANY/PRODUCT] in the [INDUSTRY] market.\n\nFor each quadrant, provide 5-7 specific, actionable items (not generic):\n\n**Strengths**: Internal advantages — what do we do better than competitors?\n**Weaknesses**: Internal limitations — what do competitors do better?\n**Opportunities**: External factors we can leverage — market trends, gaps, partnerships\n**Threats**: External risks — competitive moves, regulation, market shifts\n\nThen provide:\n- **SO Strategies** (2): Use Strengths to capitalize on Opportunities\n- **WO Strategies** (2): Address Weaknesses by leveraging Opportunities\n- **ST Strategies** (2): Use Strengths to mitigate Threats\n- **WT Strategies** (2): Minimize Weaknesses to avoid Threats\n\nMake every point specific to this company, not generic advice.', tags: ['SWOT', 'Analysis', 'Strategic Planning'] },
      { id: 'biz-3', title: 'Investor Pitch Deck Narrative', prompt: 'Write the speaker notes for a 12-slide investor pitch deck for [STARTUP] raising [AMOUNT] at [STAGE — Seed/Series A].\n\nSlide-by-slide:\n1. **Title**: Company name, one-liner, your name\n2. **Problem**: The pain, who feels it, how they cope today\n3. **Solution**: Your product — show, don\'t tell\n4. **Demo/Product**: Key screenshots or flow described\n5. **Market Size**: TAM → SAM → SOM with sources\n6. **Business Model**: Revenue model, pricing, unit economics\n7. **Traction**: Growth metrics, milestones, logos (if any)\n8. **Competition**: 2x2 matrix, your positioning\n9. **Go-to-Market**: How you acquire customers, CAC, channels\n10. **Team**: Why this team wins (relevant experience)\n11. **Financials**: 3-year projection, key assumptions\n12. **The Ask**: How much, how it\'s used, what milestones it achieves\n\nFor each slide: what to say (60 seconds), what to show, and common VC questions to anticipate.', tags: ['Pitch Deck', 'Fundraising', 'Investors'] },
      { id: 'biz-4', title: 'Competitive Analysis Framework', prompt: 'Create a detailed competitive analysis comparing [YOUR COMPANY] against [COMPETITOR 1], [COMPETITOR 2], and [COMPETITOR 3].\n\nAnalysis areas:\n1. **Product comparison**: Features matrix (✅/❌/🔶 for partial)\n2. **Pricing**: Plans, tiers, hidden costs\n3. **Target audience**: Who are they optimized for?\n4. **Strengths & Weaknesses**: Per competitor\n5. **Marketing strategy**: Channels, messaging, content approach\n6. **Customer sentiment**: Common praise and complaints (based on typical review patterns)\n7. **Market positioning map**: Place each on a 2x2 grid (suggest 2 relevant axes)\n\nDeliverables:\n- Executive summary (1 paragraph)\n- Detailed comparison table\n- 5 strategic recommendations for how to differentiate\n- Sales battlecard: For each competitor, provide "When they say X, we say Y"', tags: ['Competitive', 'Analysis', 'Battlecard'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // EDUCATION & LEARNING
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-education',
    title: 'Prompts for Education',
    description: 'Lesson plans, quizzes, study guides, and teaching materials for all levels.',
    emoji: '🎓',
    category: 'education-learning',
    promptCount: 35,
    prompts: [
      { id: 'edu-1', title: 'Lesson Plan Builder', prompt: 'Create a detailed lesson plan for teaching [TOPIC] to [GRADE LEVEL/AUDIENCE].\n\n**Lesson Overview:**\n- Subject & Topic\n- Duration: [TIME]\n- Learning Objectives (3-4, using Bloom\'s Taxonomy verbs)\n- Prerequisites: What students should already know\n- Materials needed\n\n**Lesson Structure:**\n1. **Warm-up** (5 min): Engaging opener — question, video, or activity\n2. **Direct Instruction** (15 min): Key concepts explained with analogies\n3. **Guided Practice** (15 min): Activity students do with your support\n4. **Independent Practice** (10 min): Students work on their own\n5. **Assessment** (5 min): Quick check for understanding\n6. **Wrap-up** (5 min): Summary + preview next lesson\n\n**Differentiation:** Modifications for struggling learners, advanced learners, and ELL students.\n**Homework/Extension:** Optional take-home activity.', tags: ['Lesson Plan', 'K-12', 'Teaching'] },
      { id: 'edu-2', title: 'Quiz & Assessment Generator', prompt: 'Create a comprehensive assessment for [TOPIC] at [LEVEL — beginner/intermediate/advanced].\n\nInclude:\n1. **Multiple Choice** (10 questions): 4 options each, only 1 correct. Include 1 "tricky" distractor per question that tests common misconceptions.\n2. **True/False** (5 questions): Include an explanation for why each is true or false.\n3. **Short Answer** (5 questions): Require 2-3 sentence responses. Provide a model answer and a grading rubric (what earns full/partial/no credit).\n4. **Essay** (1 question): Open-ended, requires critical thinking. Provide a rubric (4 criteria, 4-point scale).\n\nAlso provide:\n- Answer key with explanations\n- Bloom\'s Taxonomy level for each question\n- Estimated completion time\n- Suggested accommodations for students with extra time', tags: ['Quiz', 'Assessment', 'Testing'] },
      { id: 'edu-3', title: 'Study Guide Creator', prompt: 'Create a comprehensive study guide for [SUBJECT/TOPIC] covering [CHAPTERS/UNITS].\n\nFormat:\n1. **Key Concepts** (per chapter/unit): Term → definition → example → why it matters\n2. **Formulas/Rules** (if applicable): With worked examples\n3. **Comparison Tables**: Compare similar concepts side by side\n4. **Common Mistakes**: Top 5 errors students make and how to avoid them\n5. **Practice Problems**: 3 per topic (easy, medium, hard) with step-by-step solutions\n6. **Memory Aids**: Mnemonics, acronyms, or visual frameworks\n7. **Connections**: How topics relate to each other (concept map description)\n8. **Self-Test Checklist**: "I can…" statements for each learning objective\n\nMake it scannable — use bullets, bold key terms, and keep explanations under 3 sentences.', tags: ['Study Guide', 'Review', 'Exam Prep'] },
      { id: 'edu-4', title: 'Explain Like I\'m 10', prompt: 'Explain [COMPLEX TOPIC] in a way a 10-year-old would understand.\n\nRules:\n1. Use an analogy from everyday life (toys, school, sports, cooking, video games)\n2. No jargon — if you must use a technical term, define it immediately in simple words\n3. Use "imagine that…" or "it\'s like when…" to build mental pictures\n4. Break it into 3-4 small steps, each building on the last\n5. End with a fun question or mini thought experiment\n6. Maximum 200 words\n\nAfter the simple explanation, also provide:\n- A "Level Up" version for a high school student (200 words)\n- A "Deep Dive" version for an adult learner (200 words)\n- 3 follow-up questions a curious kid might ask (with answers)', tags: ['Simple', 'ELI10', 'Analogies'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // IMAGE & DESIGN
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-image-generation',
    title: 'Prompts for Image Generation',
    description: 'Midjourney, DALL-E, and Stable Diffusion prompts for stunning AI art.',
    emoji: '🎨',
    category: 'image-design',
    promptCount: 35,
    prompts: [
      { id: 'img-1', title: 'Photorealistic Image Prompt', prompt: 'Generate a photorealistic image of [SUBJECT DESCRIPTION].\n\nUse this structure:\n[Subject] + [Action/Pose] + [Setting/Background] + [Lighting] + [Camera angle] + [Lens type] + [Style modifiers]\n\nExample format:\n"A [age] [gender] [ethnicity optional] [action] in [location], [time of day] lighting, shot on [camera model], [lens mm], [f-stop], [film stock/style], [additional modifiers like bokeh, HDR, 8K]"\n\nProvide 5 variations with different:\n1. Lighting (golden hour, neon, studio, overcast, dramatic)\n2. Camera angles (low angle, bird\'s eye, close-up, wide, over-shoulder)\n3. Styles (editorial, documentary, fashion, cinematic, street photography)\n\nNote for each: which AI tool works best (Midjourney v6, DALL-E 3, or Stable Diffusion XL).', tags: ['Photorealistic', 'Photography', 'Midjourney'] },
      { id: 'img-2', title: 'Logo & Brand Identity Prompt', prompt: 'Design a logo for [BRAND NAME] — a [INDUSTRY/TYPE] company that [WHAT THEY DO].\n\nProvide 5 different prompts, each with a different style:\n\n1. **Minimalist/Modern**: Clean lines, geometric, flat design\n2. **Vintage/Retro**: Heritage feel, badge style, texture\n3. **Playful/Friendly**: Rounded shapes, warm colors, character-based\n4. **Luxury/Premium**: Elegant, serif typography, metallic accents\n5. **Tech/Futuristic**: Gradient, abstract, dynamic shapes\n\nFor each prompt include:\n- Color palette suggestion (3 colors with hex codes)\n- Typography style (serif/sans-serif/display)\n- Icon/symbol idea\n- The full AI prompt ready to paste\n- Suggested negative prompts (what to exclude)\n\nNote: Specify "vector style", "clean background", "scalable" for logo-appropriate output.', tags: ['Logo', 'Branding', 'Design'] },
      { id: 'img-3', title: 'Product Photography Prompt', prompt: 'Create AI-generated product photography for [PRODUCT TYPE] for use on [PLATFORM — e-commerce, social media, ads].\n\nProvide 6 prompt variants:\n1. **Clean studio shot**: White/gradient background, professional lighting\n2. **Lifestyle shot**: Product in use, natural environment\n3. **Flat lay**: Top-down arrangement with complementary props\n4. **Hero shot**: Dramatic angle, moody lighting, premium feel\n5. **Scale shot**: Product with reference objects for size\n6. **Seasonal/Themed**: Holiday, summer, etc. styling\n\nFor each:\n- Full prompt text ready to paste into Midjourney/DALL-E\n- Recommended aspect ratio\n- Lighting setup description\n- Prop suggestions\n- Post-processing tips (how to make AI output look more real)', tags: ['Product', 'E-commerce', 'Photography'] },
      { id: 'img-4', title: 'Social Media Graphics Prompt', prompt: 'Generate prompts for creating social media graphics for [BRAND/NICHE].\n\nCreate prompts for:\n1. **Instagram post** (1080x1080): Quote graphic with branded background\n2. **Instagram Story** (1080x1920): Announcement/promo graphic\n3. **LinkedIn banner** (1584x396): Professional header image\n4. **Twitter/X header** (1500x500): Brand identity banner\n5. **YouTube thumbnail** (1280x720): Eye-catching, high-contrast\n6. **Pinterest pin** (1000x1500): Tall, text-overlay friendly\n\nFor each:\n- Full AI prompt with dimensions, style, and colors specified\n- Text placement guidance (where to add text in post-editing)\n- Color palette that matches [BRAND COLORS or suggest based on industry]\n- 2 mood/aesthetic variants (bold & energetic vs calm & minimal)', tags: ['Social Media', 'Graphics', 'Templates'] },
    ],
  },

  {
    slug: 'prompts-for-design',
    title: 'Prompts for Design',
    description: 'UI/UX design, wireframes, color palettes, and design system prompts.',
    emoji: '🎯',
    category: 'image-design',
    promptCount: 30,
    prompts: [
      { id: 'des-1', title: 'UI/UX Design Feedback', prompt: 'Review this UI design and provide structured feedback:\n\n[DESCRIBE THE SCREEN/PAGE or paste a screenshot description]\n\nAnalyze across:\n1. **Visual Hierarchy**: Is the most important element the most prominent? Eye flow?\n2. **Consistency**: Spacing, colors, typography, button styles\n3. **Usability**: Can a user complete the primary task in under 3 clicks? Any confusion points?\n4. **Accessibility**: Color contrast, text size, touch targets (44px min), screen reader considerations\n5. **Mobile Responsiveness**: How will this adapt to smaller screens?\n6. **Micro-interactions**: What feedback does the user get? Loading states? Error states?\n7. **Copy/Labels**: Are CTAs clear? Any ambiguous labels?\n\nFor each issue, provide:\n- Severity (Critical / Important / Nice-to-have)\n- Specific suggestion with rationale\n- Reference to a design principle (Gestalt, Fitts\' Law, Nielsen heuristics)', tags: ['UI/UX', 'Feedback', 'Review'] },
      { id: 'des-2', title: 'Color Palette Generator', prompt: 'Generate a complete color palette for a [TYPE OF PRODUCT — e.g., "fintech app", "kids education platform", "luxury fashion brand"].\n\nProvide:\n1. **Primary color**: Hex, RGB, and HSL — with rationale for why this color fits the brand\n2. **Secondary color**: Complementary or analogous\n3. **Accent color**: For CTAs and highlights\n4. **Neutral scale**: 5 shades from near-white to near-black\n5. **Semantic colors**: Success (green), Warning (yellow), Error (red), Info (blue) — with specific hex values\n6. **Dark mode variant**: How each color adapts\n\nAlso include:\n- WCAG AA contrast ratios for text on each background\n- Suggested usage guidelines (when to use which color)\n- 3 gradient combinations\n- Color-blind friendly verification notes\n\nFormat as a design token table: name, hex, usage.', tags: ['Colors', 'Palette', 'Design System'] },
      { id: 'des-3', title: 'Wireframe Description Generator', prompt: 'Create a detailed wireframe description for [PAGE — e.g., "the checkout flow of a food delivery app"] that a designer can turn into a visual mockup.\n\nFor each screen provide:\n1. **Screen name and purpose**\n2. **Layout grid**: Number of columns, margins, gutters\n3. **Components list** (top to bottom):\n   - Component type (header, card, list, form, modal, etc.)\n   - Position and size (relative)\n   - Content placeholders (text, images, icons)\n   - Interactive states (default, hover, active, disabled, error)\n4. **Navigation**: How does the user get here? Where can they go next?\n5. **Edge cases**: Empty states, loading states, error states\n\nAlso provide:\n- User flow diagram (text-based: Screen A → action → Screen B)\n- Annotation notes for the developer (spacing, behavior, animations)\n- Priority markers: What\'s MVP vs. nice-to-have', tags: ['Wireframe', 'Layout', 'UX'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // PRODUCTIVITY & WORKFLOW
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-productivity',
    title: 'Prompts for Productivity',
    description: 'Time management, goal setting, daily planning, and workflow optimization.',
    emoji: '⚡',
    category: 'productivity',
    promptCount: 35,
    prompts: [
      { id: 'prod-1', title: 'Daily Planning System', prompt: 'Act as my productivity coach. Help me plan my day.\n\nHere are my tasks for today:\n[LIST YOUR TASKS]\n\nFor each task:\n1. Estimate time needed (be realistic, add 20% buffer)\n2. Assign priority: 🔴 Must do today / 🟡 Should do today / 🟢 Nice to do\n3. Assign energy level needed: High / Medium / Low\n4. Suggest best time block (match high-energy tasks to peak hours)\n\nThen create:\n- A time-blocked schedule from [START TIME] to [END TIME]\n- Include breaks (Pomodoro: 25 min work → 5 min break)\n- Identify the ONE task that will make the biggest impact if completed\n- Flag any tasks that should be delegated, automated, or dropped\n- End-of-day review prompt: 3 questions to ask yourself tonight', tags: ['Daily Planning', 'Time Blocking', 'Prioritization'] },
      { id: 'prod-2', title: 'Meeting Notes to Action Items', prompt: 'Convert these meeting notes into organized, actionable output:\n\n[PASTE RAW MEETING NOTES]\n\nGenerate:\n1. **Meeting Summary** (3-4 sentences): What was discussed and decided\n2. **Key Decisions Made**: Bulleted list with the decision and who approved it\n3. **Action Items Table**:\n   | Action | Owner | Deadline | Priority | Dependencies |\n   For each action item, make it specific and measurable (not "look into X" but "Send X report to Y by Friday")\n4. **Open Questions**: Unresolved issues that need follow-up\n5. **Parking Lot**: Topics raised but deferred to another meeting\n6. **Next Meeting**: Suggested agenda items based on today\'s discussion\n\nFormat as a clean document I can share with the team via email or Slack.', tags: ['Meetings', 'Action Items', 'Notes'] },
      { id: 'prod-3', title: 'Weekly Review Template', prompt: 'Guide me through my weekly review. Ask me these questions one section at a time:\n\n**REFLECT (Looking Back)**\n1. What were my 3 biggest wins this week?\n2. What didn\'t go as planned? Why?\n3. What did I learn?\n4. What drained my energy? What gave me energy?\n\n**REVIEW (Current State)**\n5. Review all open projects — what\'s the status of each?\n6. Are there any commitments I made that I haven\'t followed through on?\n7. Is my current workload sustainable?\n\n**PLAN (Looking Ahead)**\n8. What are my top 3 priorities for next week?\n9. What meetings can I decline or shorten?\n10. What\'s one thing I\'ll do differently next week?\n11. What\'s one thing I\'m looking forward to?\n\nAfter I answer, synthesize my responses into a "Week in Review" summary I can save.', tags: ['Weekly Review', 'Reflection', 'GTD'] },
      { id: 'prod-4', title: 'Email Inbox Zero Processor', prompt: 'Help me process my email inbox. For each email I describe, tell me:\n\n1. **Action**: Reply / Delegate / Schedule / Archive / Delete\n2. **If Reply**: Draft a response (professional, concise, under 100 words)\n3. **If Delegate**: Who to forward to and what to say\n4. **If Schedule**: When to handle it and what to add to my calendar\n5. **Priority**: Urgent / Important / Low / Noise\n\nRules:\n- If it takes less than 2 minutes, do it now (draft the reply)\n- If it requires more than 2 minutes, schedule a time block for it\n- If it\'s FYI only, archive immediately\n- If I\'m CC\'d but no action needed, archive\n\nI\'ll describe my emails one by one. Help me get to inbox zero.', tags: ['Email', 'Inbox Zero', 'Efficiency'] },
    ],
  },

  // ═══════════════════════════════════════════════════════════════
  // DATA & ANALYTICS
  // ═══════════════════════════════════════════════════════════════
  {
    slug: 'prompts-for-data-analysis',
    title: 'Prompts for Data Analysis',
    description: 'SQL queries, data visualization, statistical analysis, and reporting prompts.',
    emoji: '📊',
    category: 'data-analytics',
    promptCount: 35,
    prompts: [
      { id: 'data-1', title: 'SQL Query Generator', prompt: 'Write SQL queries for the following data questions. My database has these tables:\n\n[DESCRIBE YOUR TABLES — e.g., users (id, name, email, created_at), orders (id, user_id, total, status, created_at), products (id, name, category, price)]\n\nQuestions:\n1. [YOUR QUESTION — e.g., "What are the top 10 customers by total spend?"]\n\nFor each query provide:\n- The SQL query (formatted and commented)\n- Explanation of what each part does\n- Expected output format (column names)\n- Performance notes (will this be slow on large tables? Index suggestions)\n- A variation of the query for a slightly different use case\n\nDatabase: [PostgreSQL / MySQL / SQLite]. Use appropriate syntax.', tags: ['SQL', 'Queries', 'Database'] },
      { id: 'data-2', title: 'Data Storytelling Report', prompt: 'Turn this raw data into a compelling narrative report:\n\n[PASTE YOUR DATA / KEY METRICS]\n\nCreate:\n1. **Executive Summary** (3 sentences): The headline finding, so-what, and recommended action\n2. **Key Metrics Dashboard** (text-based): Format the top 5-7 metrics with ▲/▼ indicators and % changes\n3. **Trends Analysis**: What\'s going up, down, or staying flat? WHY?\n4. **Anomalies**: Anything unusual? Sudden spikes or drops? Possible explanations?\n5. **Segment Breakdown**: Break the data by [relevant dimension — time, geography, customer type]\n6. **Recommendations**: 3 specific actions based on the data, with expected impact\n7. **What to Watch**: 2-3 metrics to monitor closely in the next period\n\nTone: executive-friendly — no jargon, lead with insights not raw numbers. Format as a report I can share with leadership.', tags: ['Reporting', 'Storytelling', 'Insights'] },
      { id: 'data-3', title: 'Dashboard Design Spec', prompt: 'Design a [TYPE — executive / operational / marketing / sales] dashboard for [AUDIENCE].\n\nProvide:\n1. **Dashboard purpose**: What question should this dashboard answer at a glance?\n2. **KPI cards** (top row): 4-6 headline metrics with:\n   - Metric name\n   - Current value, change vs prior period\n   - Sparkline trend (describe)\n   - Red/yellow/green threshold rules\n3. **Charts** (4-6 visualizations):\n   - Chart type (line, bar, pie, heatmap, funnel, etc.) and WHY this type\n   - What data it shows\n   - Axes labels and time range\n   - Interactive features (filter, drill-down, hover tooltip)\n4. **Filters**: What should users be able to filter by?\n5. **Data sources**: What tables/APIs feed each component\n6. **Refresh frequency**: Real-time, hourly, daily?\n\nFormat as a spec document a developer could build from.', tags: ['Dashboard', 'Visualization', 'KPI'] },
      { id: 'data-4', title: 'Excel/Sheets Formula Helper', prompt: 'I need help with spreadsheet formulas. Here\'s my situation:\n\n[DESCRIBE YOUR SPREADSHEET STRUCTURE AND WHAT YOU\'RE TRYING TO CALCULATE]\n\nProvide:\n1. **The formula** (for both Google Sheets and Excel if they differ)\n2. **Step-by-step breakdown**: What each part of the formula does\n3. **Example**: Show it working with sample data\n4. **Error handling**: Wrap it to handle #N/A, #DIV/0!, empty cells\n5. **Alternative approach**: A different formula that achieves the same thing\n6. **Performance tip**: If dealing with large datasets, which approach is faster?\n\nCommon formulas I might need: VLOOKUP vs INDEX/MATCH, SUMIFS, COUNTIFS, pivot table setup, conditional formatting rules, array formulas, QUERY function (Google Sheets).', tags: ['Excel', 'Google Sheets', 'Formulas'] },
    ],
  },

  {
    slug: 'prompts-for-ecommerce',
    title: 'Prompts for E-Commerce',
    description: 'Product descriptions, reviews, pricing strategies, and store optimization.',
    emoji: '🛒',
    category: 'marketing-sales',
    promptCount: 35,
    prompts: [
      { id: 'ecom-1', title: 'Product Description Writer', prompt: 'Write a compelling product description for [PRODUCT NAME] — a [PRODUCT TYPE] priced at [PRICE].\n\nProvide:\n1. **Headline** (under 10 words): Benefit-driven, not feature-driven\n2. **Short description** (50 words): For product listings/cards\n3. **Full description** (200 words): Use the AIDA framework (Attention, Interest, Desire, Action)\n4. **Bullet points** (5-7): Features translated into benefits. Format: "[Feature] — [benefit to customer]"\n5. **SEO keywords**: 5 keywords to naturally include\n6. **Social proof line**: A one-line testimonial template\n7. **Urgency trigger**: Scarcity or time-based phrase\n\nTone: [BRAND VOICE — e.g., premium and sophisticated / friendly and casual / technical and precise].\nTarget audience: [WHO BUYS THIS].\nPlatform: [Amazon / Shopify / own website].', tags: ['Product Descriptions', 'E-commerce', 'AIDA'] },
      { id: 'ecom-2', title: 'Customer Review Response Templates', prompt: 'Create response templates for customer reviews on [PLATFORM — Amazon, Google, Yelp] for a [BUSINESS TYPE].\n\nProvide responses for:\n1. **5-star review**: Thank them, reinforce what they loved, encourage them to share\n2. **4-star review**: Thank them, ask what would make it 5 stars\n3. **3-star review**: Acknowledge, address concern, offer to make it right\n4. **2-star review**: Apologize, take responsibility, offer specific resolution\n5. **1-star review**: Professional, empathetic, move conversation offline\n6. **Fake/spam review**: Professional flag without being confrontational\n\nFor each: 3 variants (short/medium/detailed). Include:\n- What to NEVER say (legal/escalation risks)\n- Response time guidelines\n- When to offer compensation vs. just words\n- Tone: empathetic, professional, never defensive', tags: ['Reviews', 'Customer Service', 'Templates'] },
      { id: 'ecom-3', title: 'Product Launch Checklist', prompt: 'Create a comprehensive product launch checklist for launching [PRODUCT] on [PLATFORM — Shopify, Amazon, own store].\n\nPhases:\n**PRE-LAUNCH (4 weeks before)**:\n- Product listing optimization (title, descriptions, images, keywords)\n- Pricing strategy (launch price, competitor comparison, margin calculation)\n- Inventory check and fulfillment setup\n- Email list warm-up sequence\n- Social media teaser content plan\n\n**LAUNCH WEEK**:\n- Day-by-day action plan (Mon-Sun)\n- Promotional campaigns (email, social, ads)\n- Influencer/affiliate activation\n- Customer support preparation (FAQ, scripts)\n\n**POST-LAUNCH (2 weeks after)**:\n- Review collection strategy\n- Performance metrics to track (and benchmarks)\n- Retargeting campaigns\n- Iteration based on initial feedback\n\nFor each item: what to do, who owns it, and a tool suggestion.', tags: ['Launch', 'Checklist', 'Planning'] },
    ],
  },

  {
    slug: 'prompts-for-hr-hiring',
    title: 'Prompts for HR & Hiring',
    description: 'Job descriptions, interview questions, onboarding plans, and performance reviews.',
    emoji: '👥',
    category: 'business-strategy',
    promptCount: 30,
    prompts: [
      { id: 'hr-1', title: 'Job Description Generator', prompt: 'Write a compelling, inclusive job description for a [JOB TITLE] role at [COMPANY TYPE/SIZE].\n\nStructure:\n1. **Job Title**: Clear, standard (avoid internal jargon like "Ninja" or "Rockstar")\n2. **About Us** (3 sentences): Company mission, culture, what makes you different\n3. **The Role** (1 paragraph): What this person will own and why the role matters\n4. **What You\'ll Do** (6-8 bullets): Responsibilities using action verbs, specific and measurable\n5. **What You Bring** (split into):\n   - Must-haves (5-6 — only true requirements)\n   - Nice-to-haves (3-4 — clearly labeled as preferred)\n6. **What We Offer**: Compensation range, benefits, perks, growth opportunities\n7. **How to Apply**: Clear next steps\n\nInclusive language check: Avoid gendered language, unnecessary degree requirements, and "culture fit." Use "culture add" instead. Include an equal opportunity statement.', tags: ['Job Description', 'Inclusive', 'Hiring'] },
      { id: 'hr-2', title: 'Interview Question Bank', prompt: 'Create a structured interview question bank for hiring a [JOB TITLE].\n\nOrganize into rounds:\n\n**Phone Screen** (20 min, 5 questions):\n- Motivation & fit questions\n- Salary/timeline alignment\n- Red flag detection\n\n**Technical/Skills Round** (45 min, 8 questions):\n- Role-specific competency questions with follow-ups\n- Problem-solving scenario\n- "Walk me through how you would…" questions\n\n**Behavioral Round** (45 min, 6 questions):\n- STAR-format questions (Situation, Task, Action, Result)\n- Questions that reveal: collaboration, conflict resolution, ownership, learning from failure\n\n**Culture/Values Round** (30 min, 5 questions):\n- Questions aligned to company values: [LIST YOUR VALUES]\n\nFor each question: what to listen for (green flags), red flags, and a scoring rubric (1-4 scale with descriptors).', tags: ['Interview', 'Questions', 'Hiring Process'] },
      { id: 'hr-3', title: 'Onboarding Plan (30-60-90)', prompt: 'Create a 30-60-90 day onboarding plan for a new [JOB TITLE] joining [TEAM/DEPARTMENT].\n\n**First 30 Days — Learn:**\n- Week 1: Setup, meet the team, tool access, company overview\n- Week 2-4: Shadow key people, complete training modules, learn processes\n- Goals: List 3-4 specific, measurable learning objectives\n- Check-in: End of month 1 conversation — what to discuss\n\n**Days 31-60 — Contribute:**\n- Start taking ownership of small tasks/projects\n- Begin attending key meetings with a defined role\n- Goals: 3-4 specific deliverables or milestones\n- Check-in: Mid-point review — what to discuss\n\n**Days 61-90 — Own:**\n- Full ownership of core responsibilities\n- Identify one improvement or initiative to propose\n- Goals: 3-4 measurable outcomes\n- Check-in: 90-day review — success criteria for passing probation\n\nAlso include: buddy/mentor assignment, key documents to read, and a "who\'s who" stakeholder map.', tags: ['Onboarding', '30-60-90', 'New Hire'] },
    ],
  },
];

// ── Helper: get collection by slug ─────────────────────────────
export function getCollectionBySlug(slug: string): PromptCollection | undefined {
  return PROMPT_COLLECTIONS.find((c) => c.slug === slug);
}

// ── Helper: get collections by category ────────────────────────
export function getCollectionsByCategory(categoryId: string): PromptCollection[] {
  return PROMPT_COLLECTIONS.filter((c) => c.category === categoryId);
}
